---
# tasks file for ansible-role-octoprint

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create octoprint_config_dir
  file:
    path: "{{ octoprint_config_dir }}"
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_group }}"
    mode: "0700"
    state: directory

- name: Create directory for octoprint_yaml_files
  file:
    path: "{{ octoprint_config_dir }}/{{ item['path'] | dirname }}"
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_group }}"
    state: directory
  with_items: "{{ octoprint_yaml_files }}"
  when:
    - ('state' in item and item['state'] == 'present') or (not 'state' in item)

- name: Create octoprint_yaml_files
  template:
    src: yaml.j2
    dest: "{{ octoprint_config_dir }}/{{ item['path'] }}"
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_group }}"
    mode: "{% if 'mode' in item %}{{ item['mode'] }}{% else %}0600{% endif %}"
  with_items: "{{ octoprint_yaml_files }}"
  when:
    - ('state' in item and item['state'] == 'present') or (not 'state' in item)
  notify:
    - Restart octoprint

- name: Delete octoprint_yaml_files
  file:
    path: "{{ octoprint_config_dir }}/{{ item.['path'] }}"
    state: absent
  with_items: "{{ octoprint_yaml_files }}"
  when:
    - "'state' in item and item['state'] == 'absent'"

- name: Start octoprint
  service:
    name: "{{ octoprint_service }}"
    enabled: true
    state: started
