---
# tasks file for ansible-role-octoprint

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Start octoprint
  service:
    name: "{{ octoprint_service }}"
    enabled: true
    state: started
